#!/bin/bash

pr_comparison() {
  echo "GITHUB_PULL_REQUEST_EVENT_BODY:"
  echo "$GITHUB_PULL_REQUEST_EVENT_BODY"

  [[ "$GITHUB_PULL_REQUEST_EVENT_BODY" =~ $PULL_REQUEST_CONTAINS_PATTERN && ! "$GITHUB_PULL_REQUEST_EVENT_BODY" =~ $PULL_REQUEST_NOT_CONTAINS_PATTERN ]]
  BODY_IS_OK=$?

  if $BODY_IS_OK
  then
    echo "GITHUB_PULL_REQUEST_EVENT_BODY matches"

    return
  else
    echo "GITHUB_PULL_REQUEST_EVENT_BODY not matches"

    false
  fi
}
